[logging]
version = 1
disable_existing_loggers = false

[logging.root]
level = "INFO"
handlers = ["stdout", "file"]
filters = ["normalize_path"]

[logging.filters.normalize_path]
"()" = "app.core.logging.get_path_normalizer"

[logging.formatters.simple]
format = "{asctime} [{levelname:<8}|{pathname}:{lineno}] {name} - {message}"
style = "{"
datefmt = "%Y-%m-%d %H:%M:%S"

[logging.formatters.json]
"()" = "app.core.logging.JsonFormatter"
[logging.formatters.json.fmt_keys]
timestamp = "timestamp"
level = "levelname"
message = "message"
logger = "name"
module = "module"
function = "funcName"
line = "lineno"

[logging.handlers.stdout]
class = "logging.StreamHandler"
level = "INFO"
formatter = "simple"
stream = "ext://sys.stdout"
filters = ["normalize_path"]

[logging.handlers.file]
class = "logging.handlers.RotatingFileHandler"
level = "DEBUG"
formatter = "json"
filename = "logs/log.jsonl"
encoding = "utf-8"
maxBytes = 1_048_576
backupCount = 5
filters = ["normalize_path"]

[logging.handlers.disnake]
class = "logging.handlers.RotatingFileHandler"
level = "DEBUG"
formatter = "json"
filename = "logs/disnake_log.jsonl"
encoding = "utf-8"
maxBytes = 1_048_576
backupCount = 5
filters = ["normalize_path"]

[logging.loggers.disnake]
level = "DEBUG"
handlers = ["disnake"]
propagate = false
