[project]
name = "supermechs-bot"
version = "0.1.0"
description = "SuperMechs themed discord bot. Features item lookup, comparison, mech building, & more."
authors = [
    {name = "Eneg", email = "42005170+Enegg@users.noreply.github.com"},
]
dependencies = [
    "aiohttp >= 3.10.11",
    "anyio == 4.*",
    "attrs >= 23.2.0",
    "cattrs >= 24.1.2",
    "disnake >= 2.12.0",
    "disnake-ext-plugins == 0.3.*",
    "orjson >= 3.8.10",
    "psutil >= 5.9.7",
    "python-dotenv >= 1.0.0",
    "rich >= 14.0.0",
    "rtoml >= 0.9.0",
    "typing-extensions >= 4.9.0",
    "monads @ git+https://github.com/Enegg/py-monads@v0.1.3",
    "msgspec >= 0.19.0",
]
requires-python = ">= 3.13, < 3.14"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}

[project.urls]
Repository = "https://github.com/Enegg/supermechs-bot"


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = false

[tool.pdm.build]
includes = ["src/app"]


[tool.ruff]
src = ["src"]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "FIX", "TD", # todo, fixme
    "ANN401",    # use of Any
    "ARG",       # unused parameters
    "B005",      # I know str.strip(...) takes a set
    "BLE001",    # except Exception; reported in places where exceptions are gathered into a group
    "C901",      # complex functions oh no
    "CPY001",    # copyright noice
    "COM812",    # don't require commas
    "D1",        # don't require docstrings for public API
    "E501",      # line too long; => formatter
    "FBT",       # positional bool params; using inlayHints
    "F821",      # undefined variables; => pyright
    "INP001",    # no __init__.py
    "N806",      # LET ME USE CONSTANTS IN FUNCTIONS
    "N818",      # naming exceptions as *Error
    "PD",        # not using pandas
    "PLR091",    # too many ...
    "PLW0603",   # use of global; lifetime globals are ok
    "PIE796",    # non-unique enum members; => @enum.unique
    "PYI041",    # int | float isn't redundant
    "PLC0105",   # T_co / T_contra; don't care
    "PLC0414",   # import foo as foo
    "RET503",    # "return xyz(...)" where both return None is ok
    "S101",      # asserts are very useful
    "S311",      # we don't do cryptography
    "SLF001",    # _member access; => pyright
    "T201",      # print
    "TC002",     # move under TYPE_CHECKING
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]  # import *

[tool.ruff.lint.isort]
combine-as-imports = true
split-on-trailing-comma = false
extra-standard-library = ["typing_extensions"]
forced-separate = ["supermechs"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "discord",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
discord = ["disnake", "discord", "ui_store", "disnake_plugins", "app.disnake_types"]

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions", "collections.abc"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id", "format", "input", "type"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "typing.cast",
    "disnake.Color",
    "disnake.ext.commands.Param",
    "app.cattrs_utils.ByteSize",
]

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
datetime = "dt"
"discord.markdown" = "md"
"dupermechs.all" = "sm"

[tool.ruff.lint.pylint]
max-args = 8
allow-dunder-method-names = [
    "__attrs_pre_init__ ",
    "__attrs_post_init__",
    "__attrs_init__",
]

[tool.ruff.lint.flake8-tidy-imports]
banned-module-level-imports = ["app.commands.sync"]

[tool.pyright]
typeCheckingMode = "strict"
pythonVersion = "3.13"

# disabled even in strict
deprecateTypingAliases = true
reportImplicitOverride = "warning"
reportImportCycles = true
reportUninitializedInstanceVariable = true
reportUnnecessaryTypeIgnoreComment = "warning"

# prefer "# pyright: ignore[ruleName]" over "# type: ignore"
enableTypeIgnoreComments = false

# downgrade a few common non-issues
reportUnusedImport = "warning"
reportMatchNotExhaustive = "warning"
reportUnnecessaryCast = "warning"
reportUnnecessaryIsInstance = "information"

reportUnknownMemberType = false  # disnake causes plenty errors
reportUnknownVariableType = false  # gg pyright
reportMissingTypeStubs = false
