[project]
name = "supermechs-bot"
version = "0.1.0"
description = "SuperMechs themed discord bot. Features item lookup, comparison, mech building, & more."
authors = [
    {name = "Eneg", email = "42005170+Enegg@users.noreply.github.com"},
]
dependencies = [
    "anyio == 4.*",
    "attrs >= 23.2.0",
    "cattrs >= 23.2.3",
    "disnake >= 2.9.1",
    "disnake-ext-plugins @ git+https://github.com/DisnakeCommunity/disnake-ext-plugins",
    "exceptiongroup >= 1.2.2; python_version < 3.11",
    "orjson >= 3.8.10",
    "Pillow == 10.*",
    "psutil >= 5.9.7",
    "python-dotenv >= 1.0.0",
    "rtoml >= 0.9.0",
    "supermechs @ git+https://github.com/Enegg/supermechs.git",
    "typing-extensions >= 4.9.0",
]
requires-python = ">= 3.10, < 3.12"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
lint = [
    "ruff >= 0.4.2",
]


[tool.ruff]
src = ["app"]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = [
    "I",     # isort
    "E",
    "F",
    "A",     # shadowing built-ins
    "RUF",
    "UP",
    "PL",    # pylint

    "Q",     # consistent string quotes
    "FLY",   # static joins
    "ISC",   # string concatenation

    "SIM",   # simplifiable logic
    "C4",    # simplifiable comprehensions
    "PIE",   # misc

    "G",     # avoid formatting in logging
    "LOG",   # logging stuff

    "TRY",   # try - except pitfalls
    "EM",    # don't inline exception messages
    "RSE",   # skip parens on empty exceptions

    "ANN",   # annotations
    "ASYNC", # blocking calls in async context
    "TRIO",  # anyio stuff
    "TCH",   # type-checking-only imports
    "FURB",
    "PTH",   # pathlib > os.path / open
    "ERA",   # commented out code
]
ignore = [
    "ANN101", # type of self
    "ANN102", # type of cls
    "PIE796", # non-unique enums (that's a job for @unique)
    # "E501",   # line too long; handled by formatter
]

[tool.ruff.lint.pycodestyle]
max-line-length = 105

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]  # import *

[tool.ruff.lint.isort]
combine-as-imports = true
split-on-trailing-comma = false
extra-standard-library = ["typing_extensions"]
forced-separate = ["supermechs"]

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id", "format", "input"]

[tool.ruff.lint.pylint]
max-args = 8
allow-dunder-method-names = [
    "__attrs_pre_init__ ",
    "__attrs_post_init__",
    "__attrs_init__",
]


[tool.pyright]
typeCheckingMode = "strict"
include = ["app"]
exclude = ["app/dev"]

pythonVersion = "3.11"

reportUnnecessaryTypeIgnoreComment = "warning"
reportUnnecessaryCast = "warning"
reportUnnecessaryIsInstance = "information"

reportUnknownMemberType = false  # disnake causes plenty errors

deprecateTypingAliases = true
reportMissingTypeStubs = false
reportUnusedImport = "warning"

reportImportCycles = true

reportMatchNotExhaustive = "warning"
reportImplicitOverride = "warning"
reportOverlappingOverload = "warning"
reportPrivateUsage = "warning"

