[tool.black]
line-length = 100
target-version = ["py310"]


[tool.isort]
profile = "black"
py_version = 310
line_length = 100
combine_as_imports = true
filter_files = true


[tool.pyright]
typeCheckingMode = "strict"
include = ["app", "SuperMechs"]

pythonVersion = "3.10"

reportUnnecessaryTypeIgnoreComment = true
reportUnnecessaryCast = true
reportMatchNotExhaustive = "warning"

reportOverlappingOverload = false
reportPrivateUsage = false
reportUnnecessaryIsInstance = false
reportFunctionMemberAccess = false
reportImportCycles = false
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false

reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false
