[tool.ruff]
select = ["E", "F", "G", "Q", "SIM", "TCH", "PTH", "RUF", "ASYNC"]

src = ["app"]
line-length = 100
target-version = "py310"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F403"]
"api.py" = ["F403"]

[tool.ruff.isort]
combine-as-imports = true
split-on-trailing-comma = false
extra-standard-library = ["typing_extensions"]
forced-separate = ["supermechs"]

[tool.ruff.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]


[tool.pyright]
typeCheckingMode = "strict"
include = ["app"]

pythonVersion = "3.10"

reportUnnecessaryTypeIgnoreComment = true
reportUnnecessaryCast = true
reportMatchNotExhaustive = "warning"
reportUnusedImport = "warning"

reportOverlappingOverload = false
reportPrivateUsage = false
reportUnnecessaryIsInstance = false
reportFunctionMemberAccess = false
reportImportCycles = false
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false

reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false
reportMissingTypeStubs = false
