[tool.ruff]
line-length = 100
target-version = "py310"
src = ["app"]


[tool.ruff.per-file-ignores]
"__init__.py" = ["F403"]
"api.py" = ["F403"]


[tool.ruff.isort]
combine-as-imports = true
forced-separate = ["SuperMechs"]


[tool.pyright]
typeCheckingMode = "strict"
include = ["app"]

pythonVersion = "3.10"

reportUnnecessaryTypeIgnoreComment = true
reportUnnecessaryCast = true
reportMatchNotExhaustive = "warning"
reportUnusedImport = "warning"

reportOverlappingOverload = false
reportPrivateUsage = false
reportUnnecessaryIsInstance = false
reportFunctionMemberAccess = false
reportImportCycles = false
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false

reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false
reportMissingTypeStubs = false
