[project]
name = "supermechs-bot"
version = "0.1.0"
description = "SuperMechs themed discord bot. Features item lookup, comparison, mech building, & more."
authors = [
    {name = "Eneg", email = "42005170+Enegg@users.noreply.github.com"},
]
dependencies = [
    "aiohttp == 3.9.5",
    "anyio == 4.*",
    "attrs >= 23.2.0",
    "cattrs >= 24.1.2",
    "datargs >= 1.1.0",
    "disnake >= 2.10.1",
    "disnake-ext-plugins == 0.3.*",
    "orjson >= 3.8.10",
    "pillow == 10.*",
    "psutil >= 5.9.7",
    "python-dotenv >= 1.0.0",
    "rtoml >= 0.9.0",
    "typing-extensions >= 4.9.0",
    "discord-ui-store @ git+https://github.com/Enegg/discord-ui-store@v0.1.5",
    "monads @ git+https://github.com/Enegg/py-monads@v0.1.0",
    "supermechs @ git+https://github.com/Enegg/supermechs@rewrite",
]
requires-python = ">= 3.11, < 3.12"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [ "-e app @ file:///${PROJECT_ROOT}" ]
lint = [ "ruff >= 0.8.2" ]

[tool.pdm.build]
includes = ["src/app"]


[tool.ruff]
src = ["src"]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "FIX", "TD", # todo, fixme
    "ARG",       # unused parameters
    "ANN401",    # use of Any
    "B005",      # I know str.strip(...) takes a set
    "BLE001",    # catching Exception; reported in places where exceptions are gathered into a group
    "COM812",    # don't require commas
    "C901",      # complex functions oh no
    "D1",        # don't enforce docstrings for public API
    "FBT",       # positional bool params; using inlayHints
    "PLR091",    # too many ...
    "PLW0603",   # lifetime globals are ok
    "PD",        # not using pandas
    "PYI041",    # int | float isn't redundant
    "PIE796",    # non-unique enums (that's a job for @unique)
    "PLC0105",   # T_co / T_contra; don't care
    "PLC0414",   # import foo as foo
    "RET503",    # "return xyz(...)" where "xyz(...) -> None" is ok
    "S101",      # assert
    "SLF001",    # _member access; handled by pyright
    "S311",      # we don't do cryptography
    "T201",      # print
    "TC002",     # move under TYPE_CHECKING
    "N806",      # LET ME USE CONSTANTS IN FUNCTIONS
    "N818",      # naming exceptions as *Error
    "INP001",    # no __init__.py
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.pycodestyle]
max-line-length = 105

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]  # import *

[tool.ruff.lint.isort]
combine-as-imports = true
split-on-trailing-comma = false
extra-standard-library = ["typing_extensions"]
forced-separate = ["supermechs"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "discord",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
discord = ["disnake", "discord", "ui_store", "disnake_plugins", "app.disnake_types"]

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id", "format", "input"]

[tool.ruff.lint.pylint]
max-args = 8
allow-dunder-method-names = [
    "__attrs_pre_init__ ",
    "__attrs_post_init__",
    "__attrs_init__",
]


[tool.pyright]
typeCheckingMode = "strict"
pythonVersion = "3.11"

enableTypeIgnoreComments = false  # this is dumb, when enabled suggests using # type: ignore instead of # pyright: ignore[ruleName]
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnnecessaryCast = "warning"
reportUnnecessaryIsInstance = "information"

reportUnknownMemberType = false  # disnake causes plenty errors
disableBytesTypePromotions = true
deprecateTypingAliases = true
reportMissingTypeStubs = false
reportUnusedImport = "warning"

reportImportCycles = true
reportUninitializedInstanceVariable = true
reportMatchNotExhaustive = "warning"
reportImplicitOverride = "warning"
reportOverlappingOverload = "warning"
reportPrivateUsage = "warning"
