[icons]
TORSO = "https://i.imgur.com/iNtSziV.png"
LEGS = "https://i.imgur.com/6NBLOhU.png"
DRONE = "https://i.imgur.com/oqQmXTF.png"
SIDE_WEAPON_R = "https://i.imgur.com/CBbvOnQ.png"
SIDE_WEAPON_L = "https://i.imgur.com/UuyYCrw.png"
TOP_WEAPON_R = "https://i.imgur.com/LW7ZCGZ.png"
TOP_WEAPON_L = "https://i.imgur.com/1xlnVgK.png"
TELEPORTER = "https://i.imgur.com/Fnq035A.png"
CHARGE = "https://i.imgur.com/UnDqJx8.png"
HOOK = "https://i.imgur.com/8oAoPcJ.png"
MODULE = "https://i.imgur.com/dQR8UgN.png"

[gifs]
frantics = [
    "https://i.imgur.com/Bbbf4AH.mp4",
    "https://i.gyazo.com/8f85e9df5d3b1ed16b3c81dc3bccc3e9.mp4"
]
