[builds]
safe_weight = 1000
overload = 10
hp_penalty_per_kg = 15
exclusive_stats = [
    "physical_resistance",
    "explosive_resistance",
    "electric_resistance",
]

[buffs]
[buffs.energy_capacity]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.energy_regeneration]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.energy_damage]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.heat_capacity]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.heat_cooling]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.heat_damage]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.physical_damage]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.explosive_damage]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.electric_damage]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]

[buffs.physical_resistance]
type = "%"
values = [0, 2, 6, 10, 14, 18, 22, 26, 30, 34, 40]

[buffs.explosive_resistance]
type = "%"
values = [0, 2, 6, 10, 14, 18, 22, 26, 30, 34, 40]

[buffs.electric_resistance]
type = "%"
values = [0, 2, 6, 10, 14, 18, 22, 26, 30, 34, 40]

[buffs.fuel_capacity]
type = "+"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

[buffs.fuel_regeneration]
type = "%"
values = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20, 23]

[buffs.total_hp]
type = "+"
values = [0, 10, 30, 60, 90, 120, 150, 180, 220, 260, 300, 350]

[buffs.damage_vs_titans]
type = "%"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

[buffs.backfire_reduction]
type = "%"
values = [0, -1, -3, -5, -7, -9, -11, -13, -15, -17, -20]
