[stats]
[stats.weight]
in_game = "Gewicht"
[stats.health]
in_game = "Lebenspunkte"
[stats.eneCap]
in_game = "Energie"
[stats.eneReg]
in_game = "Regeneration"
[stats.heaCap]
in_game = "Hitze"
[stats.heaCol]
in_game = "Abkuehlen"
[stats.bulletCap]
in_game = "???"
[stats.rocketsCap]
in_game = "???"
[stats.phyRes]
in_game = "Physischer Widerstand"
[stats.expRes]
in_game = "Explosiver Widerstand"
[stats.eleRes]
in_game = "Elektrischer Widerstand"
[stats.phyDmg]
in_game = "Physischer Schaden"
[stats.phyResDmg]
in_game = "Widerstand reduzieren"
[stats.expDmg]
in_game = "Explosiver Schaden"
[stats.heaDmg]
in_game = "Hitze Schaden"
[stats.heaCapDmg]
in_game = "Max Hitze Schaden"
[stats.heaColDmg]
in_game = "Abkuehlen Schaden"
[stats.expResDmg]
in_game = "Widerstand reduzieren"
[stats.eleDmg]
in_game = "Elektrischer Schaden"
[stats.eneDmg]
in_game = "Energie Schaden"
[stats.eneCapDmg]
in_game = "Max Energie Schaden"
[stats.eneRegDmg]
in_game = "Regeneration Schaden"
[stats.eleResDmg]
in_game = "Widerstand reduzieren"
[stats.range]
in_game = "Reichweite"
[stats.push]
in_game = "Zurueckwerfen"
[stats.pull]
in_game = "Ziehen"
[stats.recoil]
in_game = "Ru:kstoss"
[stats.retreat]
in_game = "Ru:ckzug"
[stats.advance]
in_game = "Vorru:cken"
[stats.walk]
in_game = "Geh Distanz"
[stats.jump]
in_game = "Sprung Distanz"
[stats.uses]
in_game = "Einsaetze"
[stats.backfire]
in_game = "Backfire"
[stats.heaCost]
in_game = "Verursachte Hitze"
[stats.eneCost]
in_game = "Pobór energii"
[stats.bulletsCost]
in_game = "???"
[stats.rocketsCost]
in_game = "???"