[stats.weight]
in_game = "Gewicht"
[stats.hit_points]
in_game = "Lebenspunkte"
[stats.energy_capacity]
in_game = "Energie"
[stats.regeneration]
in_game = "Regeneration"
[stats.heat_capacity]
in_game = "Hitze"
[stats.cooling]
in_game = "Abkuehlen"
[stats.bullets_capacity]
in_game = "???"
[stats.rockets_capacity]
in_game = "???"
[stats.physical_resistance]
in_game = "Physischer Widerstand"
[stats.explosive_resistance]
in_game = "Explosiver Widerstand"
[stats.electric_resistance]
in_game = "Elektrischer Widerstand"
[stats.physical_damage]
in_game = "Physischer Schaden"
[stats.physical_resistance_damage]
in_game = "Widerstand reduzieren"
[stats.electric_damage]
in_game = "Elektrischer Schaden"
[stats.energy_damage]
in_game = "Energie Schaden"
[stats.energy_capacity_damage]
in_game = "Max Energie Schaden"
[stats.regeneration_damage]
in_game = "Regeneration Schaden"
[stats.electric_resistance_damage]
in_game = "Widerstand reduzieren"
[stats.explosive_damage]
in_game = "Explosiver Schaden"
[stats.heat_damage]
in_game = "Hitze Schaden"
[stats.heat_capacity_damage]
in_game = "Max Hitze Schaden"
[stats.cooling_damage]
in_game = "Abkuehlen Schaden"
[stats.explosive_resistance_damage]
in_game = "Widerstand reduzieren"
[stats.walk]
in_game = "Geh Distanz"
[stats.jump]
in_game = "Sprung Distanz"
[stats.range]
in_game = "Reichweite"
[stats.push]
in_game = "Zurueckwerfen"
[stats.pull]
in_game = "Ziehen"
[stats.recoil]
in_game = "Ru:kstoss"
[stats.advance]
in_game = "Vorru:cken"
[stats.retreat]
in_game = "Ru:ckzug"
[stats.uses]
in_game = "Einsaetze"
[stats.backfire]
in_game = "Backfire"
[stats.heat_generation]
in_game = "Verursachte Hitze"
[stats.energy_cost]
in_game = "???"
[stats.bullets_cost]
in_game = "???"
[stats.rockets_cost]
in_game = "???"