[stats.weight]
in_game = "Waga"
[stats.hit_points]
default = "Punkty wytrzymałości"
in_game = "Punkty życia"
[stats.energy_capacity]
default = "Pojemność energii"
in_game = "Energia"
[stats.regeneration]
in_game = "Regeneracja"
[stats.heat_capacity]
default = "Pojemność cieplna"
in_game = "Ciepło"
[stats.cooling]
in_game = "Chłodzenie"
[stats.bullets_capacity]
default = "Pojemność pocisków"
in_game = "???"
[stats.rockets_capacity]
default = "Pojemność rakiet"
in_game = "???"
[stats.physical_resistance]
in_game = "Odporność na obrażenia fizyczne"
short = "Odporność fizyczna"
[stats.explosive_resistance]
in_game = "Odporność na obrażenia wybuchowe"
short = "Odporność eksplozyjna"
[stats.electric_resistance]
in_game = "Odporność na obrażenia elektryczne"
short = "Odporność elektryczna"
[stats.physical_damage]
in_game = "Obrażenia fizyczne"
[stats.physical_resistance_damage]
in_game = "Zmniejszanie wytrzymałości"
short = "Redukcja odporności"
[stats.electric_damage]
in_game = "Obrażenia elektryczne"
[stats.energy_damage]
in_game = "Obrażenia energetyczne"
[stats.energy_capacity_damage]
default = "Redukcja pojemności energii"
in_game = "Max. obrażenia energetyczne"
[stats.regeneration_damage]
in_game = "Obrażenia regeneracji"
[stats.electric_resistance_damage]
in_game = "Zmniejszanie wytrzymałości"
short = "Redukcja odporności"
[stats.explosive_damage]
in_game = "Obrażenia wybuchowe"
[stats.heat_damage]
in_game = "Obrażenia cieplne"
[stats.heat_capacity_damage]
default = "Redukcja pojemności cieplnej"
in_game = "Max. obrażenia cieplne"
[stats.cooling_damage]
in_game = "Obrażenia chłodzenia"
[stats.explosive_resistance_damage]
in_game = "Zmniejszanie wytrzymałości"
short = "Redukcja odporności"
[stats.walk]
in_game = "Zasięg poruszania"
[stats.jump]
in_game = "Zasięg skoku"
[stats.range]
in_game = "Zasięg"
[stats.push]
default = "Pchnięcie"
in_game = "Odrzut"
[stats.pull]
in_game = "Przyciąganie"
[stats.recoil]
in_game = "Odrzut"
[stats.advance]
default = "Natarcie"
in_game = "Do przodu"
[stats.retreat]
in_game = "Odwrót"
[stats.uses]
in_game = "Liczba użyć"
short = "Użycia"
[stats.backfire]
default = "Rykoszet"
in_game = "Strzał"
[stats.heat_generation]
in_game = "Wydzielanie ciepła"
short = "Emisja ciepła"
[stats.energy_cost]
in_game = "Pobór energii"
[stats.bullets_cost]
default = "Zużycie pocisków"
in_game = "???"
[stats.rockets_cost]
default = "Zużycie rakiet"
in_game = "???"

[custom_stats.spread]
default = "Rozrzut"
[custom_stats.anyDmg]
default = "Obrażenia"
